version: "3.7"
services:
  jenkins:
    build:
      context: .
      target: jinweijie-jenkins
    image: jinweijiedocker/jenkins:latest
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
